import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
// import dynamic from "next/dynamic";
import BaseProvider from "@/providers/base_provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] })
export const metadata: Metadata = {
    title: "DApp on Solana Blockchain",
    description: "Generated by create next app by Ankur Jaiswal",
};

// const DynamicBaseProvider = dynamic(
//     async () => (await import('@/app/providers/base_provider')),
//     { ssr: false }
// );

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} antialiased dark bg-purple-950`}
            >
                <BaseProvider>
                    <div className={"w-full min-h-screen flex-1 flex items-center justify-center"}>
                        {children}
                        <Toaster />
                    </div>
                </BaseProvider>
            </body>
        </html>
    );
}
